name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.3'
        java-package: jdk
        architecture: x64
    - uses: actions/checkout@v1
    - name: Build app
      run: ./mvnw clean install jacoco:report jacoco:report-aggregate
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Extract openapi doc
      run: unzip adoptopenjdk-api-v3-frontend/target/adoptopenjdk-api-v3-frontend-*-runner.jar META-INF/quarkus-generated-openapi-doc.JSON
    - name:
      run: ../mvnw org.openapitools:openapi-generator-maven-plugin:4.2.2:generate -Dopenapi.generator.maven.plugin.inputSpec=META-INF/quarkus-generated-openapi-doc.YAML
    - name: Extract openapi doc
      run: zip javascript-client.zip target/generated-sources/openapi