name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.3'
        java-package: jdk
        architecture: x64
    - uses: actions/checkout@v1
    - name: Build app
      run: ./mvnw clean install jacoco:report jacoco:report-aggregate
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: ktlint
      uses: ScaCap/action-ktlint@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review # Change reporter
    - name: Extract openapi doc
      run: cd adoptopenjdk-api-v3-frontend && unzip target/adoptopenjdk-api-v3-frontend-*-runner.jar META-INF/quarkus-generated-openapi-doc.YAML
    - name:
      run: cd adoptopenjdk-api-v3-frontend && ../mvnw org.openapitools:openapi-generator-maven-plugin:4.2.2:generate -Dopenapi.generator.maven.plugin.inputSpec=META-INF/quarkus-generated-openapi-doc.YAML
    - name: Zip Javascript client
      run: zip javascript-client.zip adoptopenjdk-api-v3-frontend/target/generated-sources/openapi
