name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '11.0.10'
        java-package: jdk
        architecture: x64
        distribution: 'adopt'
        
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/checkout@v2

    - name: Build app
      run: ./mvnw --batch-mode clean install jacoco:report jacoco:report-aggregate

    - uses: codecov/codecov-action@v2.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Extract openapi doc
      run: |
        cd adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend
        unzip target/quarkus-app/quarkus/generated-bytecode.jar META-INF/quarkus-generated-openapi-doc.YAML
        ../../mvnw --batch-mode org.openapitools:openapi-generator-maven-plugin:4.3.0:generate \
                -Dopenapi.generator.maven.plugin.inputSpec=META-INF/quarkus-generated-openapi-doc.YAML

    - name: Parse openapi doc
      run: |
        npm i -g speccy
        # default values cannot be strings even though ours are
        sed -E 's/"([0-9]+)"/\1/g' adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/META-INF/quarkus-generated-openapi-doc.YAML > openapi.yml
        speccy lint openapi.yml

    - name: Zip Javascript client
      run: zip -r javascript-client.zip adoptopenjdk-frontend-parent/adoptopenjdk-api-v3-frontend/target/generated-sources/openapi

    - uses: actions/upload-artifact@v2
      with:
        name: javascript-client
        path: javascript-client.zip
      if: github.ref == 'refs/heads/master' && startsWith(github.repository, 'AdoptOpenJDK/')
